update

diff --git a/bin/console b/bin/console
--- a/bin/console
+++ b/bin/console
@@ -4,5 +4,11 @@ ROOT=$(git -C ${HERE} rev-parse --show-toplevel)
 SQLPLUS=$([ -x /usr/bin/rlwrap ] && echo 'rlwrap -c sqlplus' || echo 'sqlplus')
 CONNFILE="${ROOT}/tmp/sqlplus.list"
 
-[ ${#conns[@]} -eq 0 ] && echo "Connections file [${CONNFILE}] is not found" && exit 1
+[ ! -f ${CONNFILE} ] && \
+  echo "Connections file [${CONNFILE}] is not found" \
+  && exit 1
+
 conns=($(cat ${CONNFILE}))
+[ ${#conns[@]} -eq 0 ] && \
+  echo "Connections file [${CONNFILE}] is empty" \
+  && exit 1
